### ISSUE TITLE
Is it possible to use std / println?

### ISSUE THREAD

**Issue by mklan** [aarch64-switch-rs/nx#9]
Hello, first thank you for this awesome project! 

I want to create a simple terminal application. Is it possible to simply log to screen? Or do I have to stick with the graphics example.

Thanks

**Comment by XorTroll** [comment]
Since we still don't have official/std support (although [it's on its way](https://github.com/rust-lang/rust/pull/88991)), only ways of logging information are through the current graphics support (which isn't the best as it essentially uses CPU rendering) or logging via diag/macros

**Comment by mklan** [comment]
Thanks for the clarification. These are some amazing news! Would this allow us to leverage most of the crates?

**Comment by jam1garner** [comment]
> Thanks for the clarification. These are some amazing news! Would this allow us to leverage most of the crates?

That is part of the goal :)
